'use strict';
const { EmbedBuilder, PermissionFlagsBits } = require('discord.js');
const invites = require('./invites');
const panel = require('./invitesPanel');
const timers = new Map();
const operations = new Map();
function savePanelConfig(guildId, patch, meta = {}) { const section = invites.getSection(guildId); return invites.updateSettings(guildId, { publicPanel: { ...section.settings.publicPanel, ...patch } }, meta).settings.publicPanel; }
async function resolveChannel(guild, id) { const channel = id ? (guild.channels.cache.get(id) || await guild.channels.fetch(id).catch(() => null)) : null; if (!channel?.send) throw new Error('Select a text channel where Goliath can post the panel.'); const me = guild.members.me || await guild.members.fetchMe().catch(() => null); const permissions = channel.permissionsFor(me); if (!permissions?.has(PermissionFlagsBits.ViewChannel) || !permissions.has(PermissionFlagsBits.SendMessages) || !permissions.has(PermissionFlagsBits.EmbedLinks)) throw new Error(`Goliath needs View Channel, Send Messages and Embed Links in ${channel}.`); return channel; }
async function deployPublicPanel(guild, meta = {}) { const config = invites.getSection(guild.id).settings.publicPanel; const channel = await resolveChannel(guild, config.channelId); let message = config.messageId ? await channel.messages.fetch(config.messageId).catch(() => null) : null; if (message) await message.edit(panel.buildPublicPayload(guild.id)); else message = await channel.send(panel.buildPublicPayload(guild.id)); savePanelConfig(guild.id, { channelId: channel.id, messageId: message.id, lastRefreshedAt: new Date().toISOString() }, meta); return message; }
function refreshPublicPanel(guild, meta = {}) { if (operations.has(guild.id)) return operations.get(guild.id); const operation = (async () => { const config = invites.getSection(guild.id).settings.publicPanel; if (!config.channelId || !config.messageId) return false; const channel = guild.channels.cache.get(config.channelId) || await guild.channels.fetch(config.channelId).catch(() => null); const message = channel?.messages ? await channel.messages.fetch(config.messageId).catch(() => null) : null; if (!message) return false; await message.edit(panel.buildPublicPayload(guild.id)); savePanelConfig(guild.id, { lastRefreshedAt: new Date().toISOString() }, meta); return true; })().finally(() => operations.delete(guild.id)); operations.set(guild.id, operation); return operation; }
function queueLeaderboardRefresh(guild, delay = 3000) { const key = `queue:${guild.id}`; clearTimeout(timers.get(key)); timers.set(key, setTimeout(() => { timers.delete(key); refreshPublicPanel(guild, { action: 'invite_panel_refresh' }).catch(() => null); }, delay)); }
function startAutoRefresh(guild, intervalMs = invites.TWO_HOURS_MS) { const key = `interval:${guild.id}`; if (timers.has(key)) return; const timer = setInterval(() => refreshPublicPanel(guild, { action: 'invite_panel_two_hour_refresh' }).catch(() => null), intervalMs); timer.unref?.(); timers.set(key, timer); }
async function notifyInviteUsed(guild, inviterId, member) { if (!inviterId) return false; const inviter = await guild.members.fetch(inviterId).catch(() => null); if (!inviter?.user) return false; const stats = invites.getSection(guild.id).inviters[inviterId] || {}; await inviter.user.send({ embeds: [new EmbedBuilder().setColor(0x57F287).setTitle('🎉 Someone joined using your invite!').setDescription(`**${member.user?.tag || member.id}** joined **${guild.name}**.`).addFields({ name: 'Current score', value: String(Number(stats.active || 0) + Number(stats.bonus || 0)) }).setTimestamp()] }).catch(() => null); return true; }
async function trackJoin(member, meta = {}) { const result = await invites.trackJoin(member, meta); if (result) { queueLeaderboardRefresh(member.guild); if (result.inviterId) await notifyInviteUsed(member.guild, result.inviterId, member); } return result; }
async function trackLeave(member, meta = {}) { const result = await invites.trackLeave(member, meta); if (result) queueLeaderboardRefresh(member.guild); return result; }
async function startup(client) { if (client.__goliathInvitesStarted) return; client.__goliathInvitesStarted = true; for (const guild of client.guilds.cache.values()) { await invites.syncGuild(guild, { action: 'invites_startup_sync' }).catch(() => null); startAutoRefresh(guild); } }
module.exports = { savePanelConfig, deployPublicPanel, refreshPublicPanel, queueLeaderboardRefresh, startAutoRefresh, notifyInviteUsed, trackJoin, trackLeave, startup };