'use strict';
const fs=require('fs'),path=require('path'),{spawnSync}=require('child_process');
const root=path.resolve(__dirname,'..'),mode=process.env.BOT_MODE||'dev',JS=['.js','.jsx','.mjs','.cjs'];
const abs=f=>path.join(root,f),rel=f=>path.relative(root,f).replace(/\\/g,'/'),has=f=>fs.existsSync(abs(f)),read=f=>fs.readFileSync(f,'utf8');
const section=t=>{console.log(`\n${t}`);console.log('='.repeat(t.length));};
function walk(dir,ext=JS){if(!fs.existsSync(dir))return[];return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{if(['node_modules','dist','.git'].includes(e.name))return[];const f=path.join(dir,e.name);return e.isDirectory()?walk(f,ext):e.isFile()&&ext.includes(path.extname(e.name))?[f]:[];});}
function legacyCoreImports(f,s){if(!JS.includes(path.extname(f)))return[];const legacyRoot=path.join(root,'core'),legacyPrefix=`${legacyRoot}${path.sep}`,matches=[],patterns=[/require\s*\(\s*['"]([^'"]+)['"]\s*\)/g,/import\s*\(\s*['"]([^'"]+)['"]\s*\)/g,/\b(?:import|export)\s+(?:[^'";]+?\s+from\s+)?['"]([^'"]+)['"]/g];for(const pattern of patterns)for(const match of s.matchAll(pattern)){const spec=match[1];if(!spec.startsWith('.'))continue;const resolved=path.resolve(path.dirname(f),spec);if(resolved===legacyRoot||resolved.startsWith(legacyPrefix))matches.push(spec);}return[...new Set(matches)];}
function shape(){section('Project shape');const req=['server.js','package.json','scripts/goliath.js','src/commands','src/core','src/dashboard','src/events','src/modules','src/runtime','src/server'];const bad=req.filter(f=>{const ok=has(f);console.log(`${ok?'✅':'❌'} ${f}`);return!ok;});const retired=['core'],retiredFound=retired.filter(f=>has(f));retired.forEach(f=>console.log(`${has(f)?'❌':'✅'} retired /${f}`));const extras=fs.readdirSync(abs('scripts'),{withFileTypes:true}).filter(e=>e.isFile()&&e.name!=='goliath.js').map(e=>e.name);extras.forEach(f=>console.log(`❌ scripts/${f} must be absorbed`));return!bad.length&&!retiredFound.length&&!extras.length;}
function exportsAudit(title,checks){section(title);const errors=[];for(const[f,names]of checks){if(!has(f)){errors.push(`${f}: missing`);console.log(`❌ ${f}`);continue;}if(!names.length||!f.endsWith('.js')){console.log(`✅ ${f}`);continue;}try{delete require.cache[require.resolve(abs(f))];const m=require(abs(f)),missing=names.filter(n=>m?.[n]===undefined);if(missing.length)errors.push(`${f}: missing ${missing.join(', ')}`);console.log(`${missing.length?'❌':'✅'} ${f}`);}catch(e){errors.push(`${f}: ${e.message}`);console.log(`❌ ${f}`);}}errors.forEach(e=>console.log(` - ${e}`));return!errors.length;}
function commands(){section('Command audit');const seen=new Set(),errors=[];for(const f of walk(abs('src/commands'))){try{delete require.cache[require.resolve(f)];const c=require(f),n=c?.data?.toJSON?.()?.name;if(!n)throw Error('missing command name');if(seen.has(n))throw Error(`duplicate /${n}`);if(typeof c.execute!=='function')throw Error('missing execute');seen.add(n);console.log(`✅ /${n}`);}catch(e){errors.push(`${rel(f)}: ${e.message}`);console.log(`❌ ${rel(f)}`);}}errors.forEach(e=>console.log(` - ${e}`));return!errors.length;}
function source(){section('Source audit');const errors=[];for(const f of walk(root,[...JS,'.json','.md','.txt','.yml','.yaml'])){const s=read(f),r=rel(f);if(/[\u00e2\u00f0\u00ef\u00c3\ufffd]/.test(s))errors.push(`UTF-8: ${r}`);for(const spec of legacyCoreImports(f,s))errors.push(`legacy core import: ${r} -> ${spec}`);if(/\b[A-Za-z]:\\[^\r\n'"`]+/.test(s))errors.push(`Windows path: ${r}`);}errors.forEach(e=>console.log(` - ${e}`));return!errors.length;}
function imports(){section('Runtime imports');const files=[...walk(abs('src/events')),...walk(abs('src/core/admin/functions')),...walk(abs('src/server/routes')),...['src/modules/social/social.js','src/modules/social/socialPanel.js','src/modules/social/socialRoute.js'].map(abs).filter(fs.existsSync)],errors=[];const code="try{require(process.argv[1])}catch(e){console.error(e?.stack||e);process.exit(1)}";for(const f of new Set(files)){const r=spawnSync(process.execPath,['-e',code,f],{cwd:root,encoding:'utf8',timeout:15000,env:{...process.env,GOLIATH_IMPORT_AUDIT:'true'}});console.log(`${r.status===0?'✅':'❌'} ${rel(f)}`);if(r.status!==0)errors.push(`${rel(f)}: ${String(r.stderr||r.stdout).trim().split('\n').slice(0,3).join(' | ')}`);}errors.forEach(e=>console.log(` - ${e}`));return!errors.length;}
function modules(){section('Module manifest');const{MODULE_MATURITY,REQUIRED_CAPABILITIES,getMissingCapabilities,isModuleComplete}=require('../src/core/modules/moduleStandard'),{moduleManifest}=require('../src/core/modules/moduleManifest'),all=Object.values(moduleManifest),errors=[];if(all.filter(m=>m.maturity===MODULE_MATURITY.IN_PROGRESS).length!==1)errors.push('Exactly one module must be in progress');for(const m of all.sort((a,b)=>a.name.localeCompare(b.name))){const complete=isModuleComplete(m),missing=getMissingCapabilities(m);if(m.maturity===MODULE_MATURITY.COMPLETE&&!complete)errors.push(`${m.name}: missing ${missing.join(', ')}`);for(const c of REQUIRED_CAPABILITIES)if(typeof m.capabilities?.[c]!=='boolean')errors.push(`${m.name}.${c} must be boolean`);console.log(`${complete?'🟢':m.maturity===MODULE_MATURITY.IN_PROGRESS?'🟡':m.maturity===MODULE_MATURITY.PAUSED?'🔵':'⚪'} ${m.name} — ${m.maturity}`);}if(moduleManifest.social?.name!=='Social Studio')errors.push('Social must be named Social Studio');if(moduleManifest.schedule?.maturity!==MODULE_MATURITY.IN_PROGRESS)errors.push('Schedule must be active');if(moduleManifest.stats?.maturity!==MODULE_MATURITY.PAUSED||moduleManifest.tickets?.maturity!==MODULE_MATURITY.PAUSED)errors.push('Stats and Tickets must remain paused');errors.forEach(e=>console.log(` - ${e}`));return!errors.length;}
function social(){section('Social Studio architecture');const required=['providerRegistry.js','social.js','socialDelivery.js','socialHealth.js','socialHistory.js','socialManager.js','socialPanel.js','socialQueue.js','socialRoute.js','socialRuntime.js','socialScheduler.js','socialStore.js'],retired=['socialCreatorPanel.js','socialCreatorRoute.js','socialCreators.js','socialDiagnostics.js','socialSimulator.js'],errors=[],base=abs('src/modules/social');for(const f of required){const ok=fs.existsSync(path.join(base,f));console.log(`${ok?'✅':'❌'} ${f}`);if(!ok)errors.push(`missing ${f}`);}for(const f of retired){const bad=fs.existsSync(path.join(base,f));console.log(`${bad?'❌':'✅'} retired ${f}`);if(bad)errors.push(`${f} remains`);}for(const f of walk(abs('src')))for(const n of retired.map(x=>x.replace('.js','')))if(read(f).includes(n))errors.push(`${rel(f)} references ${n}`);try{delete require.cache[require.resolve(abs('src/modules/social/social.js'))];const m=require(abs('src/modules/social/social.js'));for(const n of['startup','diagnostics','delivery','creators','simulator','queue','history','health','providers','scheduler'])if(m?.[n]===undefined)errors.push(`social.js missing ${n}`);}catch(e){errors.push(`social.js: ${e.message}`);}const surfaces=exportsAudit('Social Studio surfaces',[['src/modules/social/socialPanel.js',['buildSocialAdminPanel','handleSocialAdminInteraction']],['src/modules/social/socialHealth.js',['buildHealth','repair','exportConfig','reset']],['src/modules/social/socialScheduler.js',['runSocialCheck','startSocialScheduler','handleProviderResult']],['src/commands/admin/socialhub.js',['data','execute']],['src/dashboard/js/pages/modules/Social.jsx',[]],['docs/modules/social-alerts.md',[]]]);if(!surfaces)errors.push('surface contract failed');errors.forEach(e=>console.log(` - ${e}`));return!errors.length;}
const goodbye=()=>exportsAudit('Goodbye doctor',[['src/modules/goodbye/goodbye.js',[]],['src/modules/goodbye/goodbyeDepartureDm.js',['getConfig','updateConfig','resetConfig','buildDmEmbed','sendDepartureDm']],['src/modules/goodbye/goodbyePanel.js',[]],['src/modules/goodbye/goodbyeRoute.js',[]],['docs/modules/goodbye.md',[]]]);
const reaction=()=>exportsAudit('Reaction Roles doctor',[['src/modules/roleStudio/reactionRoles/reactionRoles.js',[]],['src/modules/roleStudio/reactionRoles/reactionRolesRoute.js',[]],['src/modules/roleStudio/reactionRoles/reactionRolesPanel.js',[]],['src/dashboard/js/pages/modules/ReactionRoles.jsx',[]]]);
const roles=()=>exportsAudit('Role Studio doctor',[['src/modules/roleStudio/roleStudioPanel.js',['buildRoleStudioPanel','buildRoleAnalyticsPanel','buildRoleHealthPanel']],['src/modules/roleStudio/autoRoles/autoRoles.js',['applyAutoRoles','startupAutoRoles','buildHealthReport','setAutoRolesEnabled']],['src/modules/roleStudio/temporaryRoles/temporaryRoles.js',['assignTemporaryRole','removeAssignment','scanExpired']],['src/modules/roleStudio/timedRoles/timedRoles.js',['getMemberProgression','applyProgressionToMember','simulateGuild','scanGuild']]]);
const invites=()=>exportsAudit('Invite Studio doctor',[['src/modules/invites/invites.js',['defaults','getSection','setEnabled','updateSettings','buildHealth','repair','startup','exportConfiguration','reset']],['src/modules/invites/invitesRoute.js',[]],['src/modules/invites/invitesAdminPanel.js',['buildInviteStudioPayload','handleInviteStudioInteraction']],['src/dashboard/js/pages/modules/Invites.jsx',[]],['docs/modules/invites.md',[]]]);
function dashboard(){return exportsAudit('Dashboard entry surfaces',[['src/dashboard/js/main.jsx',[]],['src/dashboard/js/App.jsx',[]],['src/dashboard/js/ui/layout.js',[]],['src/dashboard/js/shared/moduleRegistry.js',[]]]);}
function runtime(){section('Runtime');const base=abs(`src/runtime/${mode}`);console.log(`BOT_MODE: ${mode}`);if(!fs.existsSync(base))return false;for(const f of['guilds','logs','database','data','backups'])console.log(`${fs.existsSync(path.join(base,f))?'✅':'⚠️'} ${f}`);return true;}
function guilds(){section('Guild configs');const d=abs(`src/runtime/${mode}/guilds`);if(!fs.existsSync(d))return false;fs.readdirSync(d).filter(f=>f.endsWith('.json')).sort().forEach(f=>console.log(`- ${f}`));return true;}
function media(){section('Media');const ff=spawnSync('ffmpeg',['-version']),sharp=(()=>{try{require.resolve('sharp');return true;}catch{return false;}})();console.log(`FFmpeg: ${ff.status===0?'✅':'❌'}`);console.log(`Sharp: ${sharp?'✅':'❌'}`);return ff.status===0&&sharp;}
function syncCommands(target=mode){const environment=String(target||mode).toLowerCase();if(!['dev','beta','production'].includes(environment)){console.error(`Invalid command-sync environment: ${environment}`);return false;}section(`Sync Discord commands (${environment})`);const result=spawnSync(process.execPath,[abs('src/core/commandRegistry/syncCommands.js')],{cwd:root,stdio:'inherit',env:{...process.env,BOT_MODE:environment}});return result.status===0;}
function run(command,args,options={}){const result=spawnSync(command,args,{cwd:root,stdio:'inherit',...options});if(result.error)console.error(result.error.message);return result.status===0;}
function output(command,args){const result=spawnSync(command,args,{cwd:root,encoding:'utf8'});return result.status===0?String(result.stdout||'').trim():'';}
function promote(target){const environment=String(target||'').toLowerCase(),plan={beta:{source:'dev',deploy:'/home/goliath/deploy-beta.sh'},production:{source:'beta',deploy:'/home/goliath/deploy-production.sh'}}[environment];if(!plan){console.error('Promotion target must be beta or production.');return false;}if(!fs.existsSync(abs('.git'))){console.error('Run promotion from the Goliath repository root.');return false;}if(output('git',['status','--porcelain'])){console.error('Promotion requires a clean working tree.');return false;}const original=output('git',['branch','--show-current']);if(!original){console.error('Could not determine the current branch.');return false;}section(`Promote ${plan.source} → ${environment}`);let success=false;try{if(!run('git',['fetch','origin']))return false;if(!run('git',['switch',environment]))return false;if(!run('git',['pull','--ff-only','origin',environment]))return false;if(!run('git',['merge','--no-edit',`origin/${plan.source}`]))return false;if(!doctor())return false;if(!run('git',['push','origin',environment]))return false;if(!run('ssh',['root@198.186.130.112','bash',plan.deploy]))return false;success=true;return true;}finally{if(original!==environment&&!run('git',['switch',original]))console.error(`Promotion ${success?'completed':'failed'}, but could not restore branch ${original}.`);}}
function doctor(target=''){const suites={modules,social,goodbye,reaction,reactionroles:reaction,'reaction-roles':reaction,'role-studio':roles,rolestudio:roles,invites};if(target)return suites[target]?.()??false;const results=[shape,commands,dashboard,source,imports,modules,runtime,social,goodbye,reaction,roles,invites].map(f=>f());return results.every(Boolean);}
function help(){console.log(`Goliath CLI\n===========\nMode: ${mode}\n  doctor [suite]\n  audit\n  commands\n  sync-commands [dev|beta|production]\n  promote [beta|production]\n  modules\n  social\n  goodbye\n  reaction\n  role-studio\n  invites\n  dashboard\n  runtime\n  imports\n  guilds\n  media\n  source`);}
const cmd=String(process.argv[2]||'help').toLowerCase(),target=String(process.argv[3]||'').toLowerCase(),map={help,doctor:()=>doctor(target),check:()=>doctor(target),audit:()=>{const doctorResult=doctor(),guildResult=guilds();return doctorResult&&guildResult;},commands,'sync-commands':()=>syncCommands(target),sync:()=>syncCommands(target),promote:()=>promote(target),modules,standards:modules,social,goodbye,reaction,reactionroles:reaction,'reaction-roles':reaction,'role-studio':roles,rolestudio:roles,invites,dashboard,runtime,imports,guilds,media,source};
if(!map[cmd]){console.error(`Unknown command: ${cmd}`);help();process.exit(1);}if(map[cmd]()===false)process.exit(1);