'use strict';

const Discord = require('discord.js');
const { safeReply } = require('../../../core/ui/interactionResponse');
const { fetchTarget, ensurePanelAccess, ensureActionAccess, requireModeratableTarget } = require('./permissions');
const { buildPunishmentModal, buildBulkModal, submitPunishmentRequest, submitBulkModal, createConfirmation, executePendingAction } = require('./punishments');
const { syncExpiredWarningsToCases, showWarningModal, showRemoveWarningModal, submitWarningModal, submitRemoveWarningRequest } = require('./warns');
const { openCaseTool, handleCaseAction, submitCaseModal } = require('./cases');
const { openCaseSearch, handleCaseSearchAction, handleCaseSearchSelect, handleCaseSearchModal } = require('./caseSearch');
const { refreshCasesDashboard, handleDashboardNavigation, handleUserSelectMenu, handleSelectUserButton } = require('./panel');

const PUNISHMENT_ACTIONS = new Set(['timeout', 'kick', 'ban']);
const BULK_ACTIONS = new Set(['warn', 'timeout', 'kick', 'ban']);
const OPEN_ACTIONS = new Set(['warn', ...PUNISHMENT_ACTIONS]);
function isModCustomId(customId) { const id = String(customId || ''); return id.startsWith('mod_') || id.startsWith('mod:'); }
function getTargetIdFromCustomId(customId) { return String(customId || '').split(':')[1] || 'none'; }
function getPrefixedAction(customId, prefix, allowedActions) { const id = String(customId || '').split(':')[0]; if (!id.startsWith(prefix)) return null; const action = id.slice(prefix.length); return allowedActions.has(action) ? action : null; }
function getPunishmentSubmitAction(customId) { return getPrefixedAction(customId, 'mod_submit_', PUNISHMENT_ACTIONS); }
function getBulkAction(customId) { return getPrefixedAction(customId, 'mod_submit_bulk_', BULK_ACTIONS) || getPrefixedAction(customId, 'mod_bulk_', BULK_ACTIONS); }
function parseConfirmActionContext(customId) { const parts = String(customId || '').split(':'); const requestedPage = Number(parts[5]); return { token: parts[1] || null, context: { view: parts[2] || 'overview', actionFilter: parts[3] || 'all', statusFilter: parts[4] || 'all', page: Number.isFinite(requestedPage) ? Math.max(0, Math.trunc(requestedPage)) : 0 } }; }
async function showPunishmentModal(i, action, targetId) { if (!PUNISHMENT_ACTIONS.has(action)) return false; const target = await requireModeratableTarget(i, targetId, action); if (!target) return true; await i.showModal(buildPunishmentModal(action, target.id)); return true; }
async function requestRemoveTimeout(i, targetId) { const target = await requireModeratableTarget(i, targetId, 'remove_timeout'); if (!target) return true; return createConfirmation(i, target.id, 'remove-timeout', {}, `✅ Remove timeout from **${target.user.tag}**?`); }
async function routeActionRequest(i, action, targetId) { if (action === 'warn') return showWarningModal(i, targetId); if (action === 'remove-warning') return showRemoveWarningModal(i, targetId); if (action === 'remove-timeout') return requestRemoveTimeout(i, targetId); if (PUNISHMENT_ACTIONS.has(action)) return showPunishmentModal(i, action, targetId); return false; }
async function handleActionSelectMenu(i) { if (!i.customId.startsWith('mod_action_select:')) return false; return routeActionRequest(i, i.values[0], getTargetIdFromCustomId(i.customId)); }
async function handleOpenActionButton(i) { const action = getPrefixedAction(i.customId, 'mod_open_', OPEN_ACTIONS); if (!action) return false; return routeActionRequest(i, action, getTargetIdFromCustomId(i.customId)); }
async function handleCaseToolButton(i) { const caseResult = await openCaseTool(i); if (caseResult) return caseResult; const searchResult = await handleCaseSearchAction(i); if (searchResult) return searchResult; const id = String(i.customId || ''); const targetId = getTargetIdFromCustomId(id); if (id.startsWith('mod_remove_warning:')) return routeActionRequest(i, 'remove-warning', targetId); if (id.startsWith('mod_remove_timeout:')) return routeActionRequest(i, 'remove-timeout', targetId); return false; }
async function handleBulkButton(i) { if (!String(i.customId || '').startsWith('mod_bulk_')) return false; const action = getBulkAction(i.customId); if (!action) return false; const allowed = await ensureActionAccess(i, `bulk_${action}`, `❌ No permission to use bulk ${action}.`); if (!allowed) return true; await i.showModal(buildBulkModal(action)); return true; }
async function handleConfirmButton(i) { if (!i.customId.startsWith('mod_confirm_action:')) return false; const { token, context } = parseConfirmActionContext(i.customId); return executePendingAction(Discord, i, token, context); }
async function handleCancelButton(i) { if (i.customId !== 'mod_cancel_action') return false; if (i.message && typeof i.update === 'function') { await i.update({ content: '❌ Cancelled.', embeds: [], components: [] }); return true; } return safeReply(i, { content: '❌ Cancelled.', flags: 64 }); }
async function handleBulkModal(i) { if (!String(i.customId || '').startsWith('mod_submit_bulk_')) return false; const action = getBulkAction(i.customId); if (!action) return false; const allowed = await ensureActionAccess(i, `bulk_${action}`, `❌ No permission to use bulk ${action}.`); if (!allowed) return true; return submitBulkModal(i, action); }
async function handleActionModal(i) { const id = String(i.customId || ''); const targetId = getTargetIdFromCustomId(id); if (id.startsWith('mod_submit_warn:')) return submitWarningModal(i, targetId, refreshCasesDashboard); if (id.startsWith('mod_submit_remove_warning:')) return submitRemoveWarningRequest(i, targetId, createConfirmation); const action = getPunishmentSubmitAction(id); if (!action) return false; const target = await requireModeratableTarget(i, targetId, action); if (!target) return true; const result = await submitPunishmentRequest(i, target, action); if (action === 'timeout' && result?.ok) await refreshCasesDashboard(i, target); return true; }
async function routeHandlers(i, handlers) { for (const handler of handlers) { const result = await handler(i); if (result) return result; } return false; }
async function routeButtonsAndSelects(i) { const denied = ensurePanelAccess(i); if (denied) return denied; if (i.isUserSelectMenu?.()) return handleUserSelectMenu(i); if (i.isStringSelectMenu?.()) return routeHandlers(i, [handleCaseSearchSelect, handleActionSelectMenu]); if (!i.isButton?.()) return false; return routeHandlers(i, [handleConfirmButton, value => handleCaseAction(value, { fetchTarget, createConfirmation }), handleDashboardNavigation, handleCancelButton, handleSelectUserButton, handleBulkButton, handleOpenActionButton, handleCaseToolButton]); }
async function routeModModal(i) { if (!i?.customId?.startsWith('mod_')) return false; const denied = ensurePanelAccess(i); if (denied) return denied; await syncExpiredWarningsToCases(i.guild.id); return routeHandlers(i, [handleCaseSearchModal, value => submitCaseModal(value, { fetchTarget, refreshCasesDashboard }), handleBulkModal, handleActionModal]); }
async function handleModInteraction(i) { if (!i?.customId || !isModCustomId(i.customId)) return false; if (i.customId.startsWith('nav|')) return false; if (i.isModalSubmit?.()) return routeModModal(i); return routeButtonsAndSelects(i); }
module.exports = { handleModInteraction };
