export const MODULE_CATEGORIES = {
  feature: 'Features',
};

export const MODULE_STATUSES = {
  live: 'Live',
  backendReady: 'Backend Ready',
  uiPending: 'UI Pending',
  planned: 'Planned',
};

export const MODULE_STATUS_META = {
  [MODULE_STATUSES.live]: {
    label: 'Live',
    tone: 'success',
  },
  [MODULE_STATUSES.backendReady]: {
    label: 'Backend Ready',
    tone: 'info',
  },
  [MODULE_STATUSES.uiPending]: {
    label: 'Coming Soon',
    tone: 'warning',
  },
  [MODULE_STATUSES.planned]: {
    label: 'Coming Soon',
    tone: 'muted',
  },
};

export const moduleRegistry = [
  {
    key: 'aiAssistant',
    name: 'AI Assistant',
    icon: 'AI',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — AI-powered admin support, summaries and smart actions.',
  },
  {
    key: 'appeals',
    name: 'Appeals',
    icon: 'AP',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — appeal forms, review queues and staff decisions.',
  },
  {
    key: 'applications',
    name: 'Applications',
    icon: 'AJ',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — staff, partner and community application workflows.',
  },
  {
    key: 'autoRoles',
    name: 'Auto Roles',
    icon: 'AR',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Assign roles automatically when members join or meet conditions.',
  },
  {
    key: 'birthdays',
    name: 'Birthdays',
    icon: 'BD',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — birthday tracking and automated celebration messages.',
  },
  {
    key: 'boostRewards',
    name: 'Boost Rewards',
    icon: 'BR',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — server boost rewards, roles and recognition tools.',
  },
  {
    key: 'customCommands',
    name: 'Custom Commands',
    icon: 'CC',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — create custom slash commands and reusable responses.',
  },
  {
    key: 'economy',
    name: 'Economy',
    icon: 'EC',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — currency, rewards, shops and community economy tools.',
  },
  {
    key: 'embedStudio',
    name: 'Embed Studio',
    icon: 'ES',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Create, save, test and deploy custom Discord embeds.',
  },
  {
    key: 'events',
    name: 'Events',
    icon: 'EV',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — event planning, reminders and attendance tracking.',
  },
  {
    key: 'forms',
    name: 'Forms',
    icon: 'FM',
    route: '/forms',
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.backendReady,
    enabled: true,
    summary: 'Universal forms, submissions, analytics and workflow foundations.',
  },
  {
    key: 'giveaways',
    name: 'Giveaways',
    icon: 'GW',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Create and manage server giveaways.',
  },
  {
    key: 'leveling',
    name: 'Leveling',
    icon: 'LV',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — XP, levels, leaderboards and activity rewards.',
  },
  {
    key: 'mediaFeeds',
    name: 'Media Feeds',
    icon: 'MF',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — YouTube, Twitch, TikTok and social feed announcements.',
  },
  {
    key: 'memberReports',
    name: 'Member Reports',
    icon: 'MR',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — member report forms and staff review workflows.',
  },
  {
    key: 'music',
    name: 'Music',
    icon: 'MU',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — music playback and voice channel controls.',
  },
  {
    key: 'polls',
    name: 'Polls',
    icon: 'PL',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — polls, votes and community decisions.',
  },
  {
    key: 'reactionRoles',
    name: 'Reaction Roles',
    icon: 'RR',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — reaction and button-based role panels.',
  },
  {
    key: 'roles',
    name: 'Roles',
    icon: 'RL',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Role utilities, role automation and future reaction-role controls.',
  },
  {
    key: 'scheduledMessages',
    name: 'Scheduled Messages',
    icon: 'SD',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — scheduled announcements and recurring messages.',
  },
  {
    key: 'starboard',
    name: 'Starboard',
    icon: 'ST',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Highlight popular server messages in a starboard channel.',
  },
  {
    key: 'status',
    name: 'Status',
    icon: 'SS',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — server or bot status module controls.',
  },
  {
    key: 'sticky',
    name: 'Sticky Messages',
    icon: 'SM',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Keep important channel messages pinned to the bottom of chat.',
  },
  {
    key: 'suggestions',
    name: 'Suggestions',
    icon: 'SG',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — collect, review and manage community suggestions.',
  },
  {
    key: 'tempVoice',
    name: 'Temp Voice',
    icon: 'TV',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Temporary voice channels and voice room automation.',
  },
  {
    key: 'tickets',
    name: 'Tickets',
    icon: 'TK',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Ticket panels, claims, closing, transcripts, recovery and analytics.',
  },
  {
    key: 'timeline',
    name: 'Timeline',
    icon: 'TL',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Timeline storage and timeline-driven server updates.',
  },
  {
    key: 'translation',
    name: 'Translation',
    icon: 'TR',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Language preferences, provider-ready storage and translation controls.',
  },
  {
    key: 'verification',
    name: 'Verification',
    icon: 'VF',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — member verification and onboarding protection.',
  },
  {
    key: 'welcomeLeave',
    name: 'Welcome & Leave',
    icon: 'WL',
    route: null,
    category: MODULE_CATEGORIES.feature,
    status: MODULE_STATUSES.planned,
    enabled: false,
    summary: 'Coming soon — welcome, leave and onboarding message controls.',
  },
].sort((a, b) => a.name.localeCompare(b.name));

export const futureModules = [];

export function getModuleStatusMeta(status) {
  return MODULE_STATUS_META[status] || MODULE_STATUS_META[MODULE_STATUSES.planned];
}

export default moduleRegistry;
