export const MODULE_CATEGORIES = {
  core: 'Core',
  security: 'Security',
  support: 'Support',
  community: 'Community',
  automation: 'Automation',
  utility: 'Utility',
  operations: 'Operations',
};

export const MODULE_STATUSES = {
  live: 'Live',
  backendReady: 'Backend Ready',
  uiPending: 'UI Pending',
  planned: 'Planned',
};

export const MODULE_STATUS_META = {
  [MODULE_STATUSES.live]: {
    label: 'Live',
    tone: 'success',
  },
  [MODULE_STATUSES.backendReady]: {
    label: 'Backend Ready',
    tone: 'info',
  },
  [MODULE_STATUSES.uiPending]: {
    label: 'UI Pending',
    tone: 'warning',
  },
  [MODULE_STATUSES.planned]: {
    label: 'Planned',
    tone: 'muted',
  },
};

export const moduleRegistry = [
  {
    key: 'generalSettings',
    name: 'General Settings',
    icon: 'GS',
    route: '/generalSettings',
    category: MODULE_CATEGORIES.core,
    status: MODULE_STATUSES.live,
    enabled: true,
    summary: 'Core guild configuration and shared server settings.',
    priority: 10,
  },
  {
    key: 'security',
    name: 'Security Center',
    icon: 'SC',
    route: '/security',
    category: MODULE_CATEGORIES.security,
    status: MODULE_STATUSES.live,
    enabled: true,
    summary: 'Lockdown, quarantine, restore access and live protection overview.',
    priority: 20,
  },
  {
    key: 'restore',
    name: 'Restore',
    icon: 'RS',
    route: '/restore',
    category: MODULE_CATEGORIES.operations,
    status: MODULE_STATUSES.live,
    enabled: true,
    summary: 'Preview and restore server recovery points.',
    priority: 30,
  },
  {
    key: 'logs',
    name: 'Logs',
    icon: 'LG',
    route: '/logs',
    category: MODULE_CATEGORIES.operations,
    status: MODULE_STATUSES.live,
    enabled: true,
    summary: 'Logging configuration and server activity visibility.',
    priority: 40,
  },
  {
    key: 'forms',
    name: 'Forms',
    icon: 'FM',
    route: '/forms',
    category: MODULE_CATEGORIES.support,
    status: MODULE_STATUSES.backendReady,
    enabled: true,
    summary: 'Universal forms, submissions, analytics and workflow foundations.',
    priority: 50,
  },
  {
    key: 'welcomeLeave',
    name: 'Welcome & Leave',
    icon: 'WL',
    route: '/messages',
    category: MODULE_CATEGORIES.community,
    status: MODULE_STATUSES.live,
    enabled: true,
    summary: 'Configure join and leave messages for the selected server.',
    priority: 60,
  },
  {
    key: 'autoMod',
    name: 'AutoMod',
    icon: 'AM',
    route: '/automod',
    category: MODULE_CATEGORIES.security,
    status: MODULE_STATUSES.live,
    enabled: true,
    summary: 'Moderation filters and automated rule controls.',
    priority: 70,
  },
  {
    key: 'tickets',
    name: 'Tickets',
    icon: 'TK',
    route: null,
    category: MODULE_CATEGORIES.support,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Ticket creation, claims, closing, transcripts, recovery and analytics. Dashboard UI pending.',
    priority: 80,
  },
  {
    key: 'translation',
    name: 'Translation',
    icon: 'TR',
    route: null,
    category: MODULE_CATEGORIES.utility,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Language preferences, dashboard APIs and provider-ready storage. Hub UI pending.',
    priority: 90,
  },
  {
    key: 'embedStudio',
    name: 'Embed Studio',
    icon: 'ES',
    route: null,
    category: MODULE_CATEGORIES.community,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Builder, previews, presets, buttons, footer editor and deployment tracking.',
    priority: 100,
  },
  {
    key: 'autoRoles',
    name: 'Auto Roles',
    icon: 'AR',
    route: null,
    category: MODULE_CATEGORIES.automation,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Role module storage exists. Dashboard controls are pending.',
    priority: 110,
  },
  {
    key: 'giveaways',
    name: 'Giveaways',
    icon: 'GW',
    route: null,
    category: MODULE_CATEGORIES.community,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Giveaway storage and scheduler are ready for dashboard UI.',
    priority: 120,
  },
  {
    key: 'tempVoice',
    name: 'Temp Voice',
    icon: 'TV',
    route: null,
    category: MODULE_CATEGORIES.community,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Temporary voice module storage exists. Management UI is pending.',
    priority: 130,
  },
  {
    key: 'starboard',
    name: 'Starboard',
    icon: 'ST',
    route: null,
    category: MODULE_CATEGORIES.community,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Starboard configuration is stored in guild JSON.',
    priority: 140,
  },
  {
    key: 'sticky',
    name: 'Sticky Messages',
    icon: 'SM',
    route: null,
    category: MODULE_CATEGORIES.utility,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Sticky message storage is migrated into guild JSON.',
    priority: 150,
  },
  {
    key: 'timeline',
    name: 'Timeline',
    icon: 'TL',
    route: null,
    category: MODULE_CATEGORIES.utility,
    status: MODULE_STATUSES.backendReady,
    enabled: false,
    summary: 'Timeline module storage is migrated into guild JSON.',
    priority: 160,
  },
  {
    key: 'analytics',
    name: 'Analytics',
    icon: 'AN',
    route: null,
    category: MODULE_CATEGORIES.operations,
    status: MODULE_STATUSES.uiPending,
    enabled: false,
    summary: 'Cross-module statistics and reporting hub.',
    priority: 170,
  },
  {
    key: 'backups',
    name: 'Backup Center',
    icon: 'BC',
    route: null,
    category: MODULE_CATEGORIES.operations,
    status: MODULE_STATUSES.uiPending,
    enabled: false,
    summary: 'Backup history, restore points and future diff viewer.',
    priority: 180,
  },
];

export const futureModules = [
  'AI Assistant',
  'Applications',
  'Appeals',
  'Economy',
  'Leveling',
  'Music',
  'Reaction Roles Rework',
  'Verification',
];

export function getModuleStatusMeta(status) {
  return MODULE_STATUS_META[status] || MODULE_STATUS_META[MODULE_STATUSES.planned];
}

export default moduleRegistry;
